name: Build Metrolist Release (ARM64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Unzip Metrolist project
        run: |
          unzip Metrolist-12.12.4.zip
          ls -la

      - name: FIX permissions (important)
        run: |
          chmod -R u+rwX Metrolist-12.12.4

      - name: Verify access
        run: |
          cd Metrolist-12.12.4
          ls -la

      - name: Make gradlew executable
        run: |
          cd Metrolist-12.12.4
          chmod +x gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build ARM64 GMS Release APK
        env:
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_SECRET: ${{ secrets.LASTFM_SECRET }}
        run: |
          cd Metrolist-12.12.4
          ./gradlew :app:assembleArm64GmsRelease --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Metrolist-arm64-gms-release
          path: Metrolist-12.12.4/app/build/outputs/apk/**/arm64*gms*release*.apk
