name: Build Metrolist Universal Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Show repository files
        run: ls -la

      - name: Unzip Metrolist project
        run: unzip Metrolist-Modified.zip

      - name: Fix permissions after unzip
        run: |
          chmod -R u+rwX Metrolist-12.12.4

      - name: Make gradlew executable
        run: chmod +x Metrolist-12.12.4/gradlew

      - name: Verify gradlew
        run: ls -la Metrolist-12.12.4/gradlew

      - name: Build UNIVERSAL GMS RELEASE
        run: |
          cd Metrolist-12.12.4
          ./gradlew :app:assembleUniversalGmsRelease --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Metrolist-Universal-GMS-Release
          path: Metrolist-12.12.4/app/build/outputs/apk/**/release/*.apk
