name: Build Metrolist Universal Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: List repository files
        run: ls -la

      - name: Unzip Metrolist project
        run: unzip Metrolist-Modified.zip

      - name: Detect project directory
        run: |
          PROJECT_DIR=$(find . -maxdepth 1 -type d -name "Metrolist*" | head -n 1)
          echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV
          echo "Using project dir: $PROJECT_DIR"

      - name: Make gradlew executable
        run: chmod +x $PROJECT_DIR/gradlew

      - name: Build UNIVERSAL GMS RELEASE APK
        run: |
          cd $PROJECT_DIR
          ./gradlew :app:assembleUniversalGmsRelease --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Metrolist-Universal-GMS-Release
          path: |
            ${{ env.PROJECT_DIR }}/app/build/outputs/apk/**/release/*.apk
